spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exceldata
    username: postgres
    password: root

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update






app:
  upload:
   file: "C:/Users/avramazanli/IdeaProjects/ExcelImportExport/files/UserReportTest.xlsx"
server:
  port: 8081



