spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exceldata
    username: postgres
    password: root

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update




  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

#app:
#  upload:
#    dir: './files/UserExcel_20.xlsx'
#    file: UserExcel_20.xlsx

